modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
displayURL="https://space.bilibili.com/351674558?spm_id_from=333.1007.0.0"
authors="ooowakaka"
description='''
关注up查看最新版本:https://space.bilibili.com/351674558?spm_id_from=333.788.0.0
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="optional"
versionRange="[6.0,)"
ordering="NONE"
side="CLIENT"
